/*
 * sensor_telemetry.h
 *
 *  Created on: 1 Jan 2026
 *      Author: Chris Thompson, VE2TCP
 */

#ifndef SENSOR_TELEMETRY_H_
#define SENSOR_TELEMETRY_H_

/**
 * This structure is generated by the python gen_header.py script from a csv file.  Change the layout in that tool
 * and re-generate this structure
 */

typedef struct __attribute__((__packed__)) {
    unsigned int timestamp : 32;
    unsigned int LPS22_pressure : 32;
    unsigned int LPS22_temp : 16;
    unsigned int O2_conc : 16;
    unsigned int CO2_conc : 16;
    unsigned int O2_raw : 16;
    unsigned int methane_conc : 16;
    unsigned int air_quality : 16;
    unsigned int SHTC3_temp : 16;
    unsigned int SHTC3_humidity : 16;
    unsigned int AccelerationX : 16;
    unsigned int AccelerationY : 16;
    unsigned int AccelerationZ : 16;
    unsigned int GyroX : 16;
    unsigned int GyroY : 16;
    unsigned int GyroZ : 16;
    unsigned int MagX : 16;
    unsigned int MagY : 16;
    unsigned int MagZ : 16;
    unsigned int IMUTemp : 16;
    unsigned int cw_raw_count : 16;
    unsigned int cw_coincident_count : 16;
    unsigned int cw_raw_rate : 16;
    unsigned int cw_coincident_rate : 16;
    unsigned int light_level : 8;
    unsigned int max_sound_level : 8;
    unsigned int light_RGB : 32;
    unsigned int max_sound_bin : 8;
    unsigned char sound_psd[32];
    unsigned int co2_sensor_valid : 2;
    unsigned int o2_sensor_valid : 2;
    unsigned int methane_sensor_valid : 2;
    unsigned int air_q_sensor_valid : 2;
    unsigned int cw_raw_valid : 2;
    unsigned int cw_coincident_valid : 2;
    unsigned int microphone_valid : 2;
    unsigned int ImuValid : 2;
    unsigned int TempHumidityValid : 2;
    unsigned int PressureValid : 2;
    unsigned int ColorValid : 2;
    unsigned int Pad1 : 2;
} sensor_telemetry_t;


#endif /* SENSOR_TELEMETRY_H_ */
